### ISSUE TITLE
Milestone 1 on 2016/03/09

### ISSUE THREAD

**Issue by hermantai** [FearlessApp/Fearless#20]
https://github.com/FearlessApp/Fearless

Look at the bottom to see the gif and the user stories for the milestone.

/cc @codepathreview @codepath

**Comment by codepathreview** [comment]
:+1: Nice work creating tasks for sprint 1. The goal of this sprint is to have the basic screens and workflows ready as much as possible. A few notes

* Tasks are well defined and seem achievable in the given timeframe
* Good work dividing tasks among team members. This is critical in working as a team and also gives equal learning opportunity to everyone involved
* Consider diving a bigger parent task into a number of smaller subtasks - provides a better picture of the progress on the issue
* Good to see that everyone is [contributing](https://github.com/FearlessApp/Fearless/graphs/contributors) to the project. This is critical in working as a team and also gives equal learning opportunity to everyone involved.
* Good to see that your team created regular commits to sync up your code to avoid having multiple conflicts at the end.
* Good job creating milestones, so that its easier for you to track progress of the project.
* Consider creating tasks to QA the app a few times to check the basic flow. Integration testing will especially be important for this project since each team member is working on a separate module. The best part is seeing it all come together into a polished app.

Good to see the basic flow coming along well. Please take notes of these points and improve upon the same in the next sprint. Look forward to the rest of the functionality and improvement on the core flows by the end of the Sprint 2 so you can have enough time to add UI polish and advanced nice-to-have features later on. It is those little extra things you do that make everything feel more polished and desirable to use.
